site_name: avalayers
site_description: A unified pipeline for FlowPy avalanche simulations
site_author: Paul

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
    - yaml

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.] # Allow mkdocstrings to find the avalayers package in the current dir

nav:
  - Home: index.md
  - User Guide: user_guide.md
  - API Reference: api.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
